// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwkbzkgnddtmimovvuho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3a2J6a2duZGR0bWltb3Z2dWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODgzMzIsImV4cCI6MjA2OTU2NDMzMn0.qzsV1OrB5GQmoSPUh1SQveTglurCIqY--IySwjnm-M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});